### ISSUE TITLE
Idea: Reduce the EMC multiplier per tier from 2^42 to 10^12

### ISSUE THREAD

**Issue by James103** [62832/AppliedE#1]
Powers of 2^42, while understandable to computers, are hard for humans (players) to understand and recognize quickly, while powers of 10^12 are much more recognizable and understandable for humans using the base-10 counting system.

For example, if an ME EMC Module placed by a given player reports that the player has 5,972,200,000,000,000,224,395,264 EMC available, that will be split as 1,357,921,064,482 EMC^2 units and 310,311,387,136 EMC units, which can be hard for some players to relate to the original EMC total.

With the change, the same 5,972,200,000,000,000,224,395,264 EMC will now split into 5 EMC^3 units, 972,200,000,000 EMC^2 units, and 224,395,264 EMC units. This makes it much easier for players to relate to the original EMC total, as now each EMC^N unit corresponds to exactly 12 digits of their EMC total, with no base conversion necessary.

This can be implemented simply by replacing `Math.pow(2, 42)` with `Math.pow(10, 12)` here: https://github.com/62832/AppliedE/blob/b8936a75592df33afec6e8c1dc74c2a565125d1e/src/main/java/gripe/_90/appliede/AppliedE.java#L57

A side effect of this is a slight further reduction of overflow risk, as 10^12 is about 4 times smaller than 2^42.

**Comment by 62832** [comment]
That's actually a pretty good idea. The only reason I had it as 2^42 was because I ripped it from the same stack limit as MEGA Cells and its bulk compression system. This would be much better to use instead.
