### ISSUE TITLE
Division by 0 error

### ISSUE THREAD

**Issue by HEROgold** [62832/AppliedE#16]
Sadly i don't have the logs since this happened on a public server.
However using ae2 and AppliedE, whenever my base gets loaded in, there happens to be a division by 0 crash. I only use the Emc Module attached to my AE2 network.

**Comment by 62832** [comment]
What version are you using? This may be a duplicate of #15.

**Comment by HEROgold** [comment]
appliede-0.13.1-beta.jar, it's from the ATM9 to the skies modpack (V 1.0.6)

**Comment by HEROgold** [comment]
after taking a look at issue 15, looks to be the same problem

**Comment by 62832** [comment]
Then update to 0.13.2/.3. It's been fixed already.
