### ISSUE TITLE
[Incompatibility] Versions 0.3.* couse Tooltip Conflict with AE Additions - ExtraCells2 Fork

### ISSUE THREAD

**Issue by OliStab** [62832/AppliedE#2]
With Versions 0.3.0, 0.3.1, 0.3.2, and 0.3.3 I get a Tooltip Error.

```
[16:16:23] [Render thread/ERROR]: Caught an error rendering an Ingredient's tooltip:

-- Ingredient --
Details:
	Name: 1k ME Super Storage Cell
	Mod's Name: AE Additions
	Registry Name: ae2additions:super_cell_1k
	Class Name: class net.minecraft.world.item.ItemStack
	toString Name: 1 super_cell_1k
	Unique Id for JEI (for JEI Blacklist): ae2additions:super_cell_1k
	Ingredient Type for JEI: class net.minecraft.world.item.ItemStack
	Error Info gathered from JEI: 1 super_cell_1k ae2additions:super_cell_1k nbt:{}

-- Stack Trace --

java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.getString()" because the return value of "appeng.api.stacks.AEKeyType.getDescription()" is null
```

Disabling AppliedE or downgrading to Version 0.2.5 fixes the Issue for me.

[latest.log](https://github.com/62832/AppliedE/files/15177970/latest.log)

**Comment by 62832** [comment]
That's weird. Would you try again on the most recent version, but disable the EMC mappers AppliedE adds? They should be under ProjectE's `mapping.toml` and `nbt.toml` configs.

**Comment by 62832** [comment]
In fact, to be more specific, does this happen when the `AE2CellProcessor` in `nbt.toml` is disabled?

**Comment by OliStab** [comment]
Hmm, can't find a nbt.toml file.
And in the mapping.toml file I can't seem to find AppliedE specific Options.

I deactivated AE2P2PTunnels under enabledMappers and CraftingMapper.AppliedEnergisticsInscriberMapper.

With that running 0.3.3 returns the Error.

**Comment by 62832** [comment]
I'm very sorry, I meant `processing.toml`, not `nbt.toml`.

**Comment by OliStab** [comment]
No worries.

With Version 0.3.3 and all AE2 Options I could find in the files tuned off , the error is still there.

```
mapping.toml:

[enabledMappers]
    AE2P2PTunnels = false // was true

[CraftingMapper]
    [CraftingMapper.AppliedEnergisticsInscriberMapper]
        enabled = false // was true
	
    [CraftingMapper.AE2Transform]
		enabled = false // was false

	[CraftingMapper.AE2Inscriber]
		enabled = false // was false

	[CraftingMapper.AE2Charger]
		enabled = false // was false


processing.toml:

[processors]
    [processors.AE2CellProcessor]
		enabled = false // was true

	[processors.AE2NetworkToolProcessor]
		enabled = false // was true
```

I didn't touch the Priority and Permission Options.

**Comment by 62832** [comment]
Well that's frustrating. I'll try to investigate further.

**Comment by OliStab** [comment]
Since I write Code for a living, I fell you. Take your time.

FYI I tried it the other way round, with AppliedE 0.3.3 and AE Additions turned off and the Options reset to default, the error disappears. Only with both on it occurs.

**Comment by 62832** [comment]
I got it, but I have no idea why the fix I've put in place even works when things should also (in theory) work just fine without it. Hotfix will be coming right away.

**Comment by 62832** [comment]
Oh, I know why it didn't work prior. I guess field access came into play here without me realising.
