### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by TheOddball** [62832/AppliedE#3]
Hello Ninety!

It appears as though AppliedE is crashing my Minecraft server. I have uploaded the crashlog below. ~~Unfortunately, due to the nature of this crash, I cannot login in order to investigate exact details of my setup.~~

I have gotten back into my server and identified the main steps to get this crash to occur. I currently have 1.8G of EMC in my Table, and specifically what I did to cause this crash was; Enter the portal in The End (returning to overworld). I avoided this crash by manually editing my player NBT data back to overworld from the_end.

[crash-2024-05-05_02.23.34-server.txt](https://github.com/62832/AppliedE/files/15212387/crash-2024-05-05_02.23.34-server.txt)

**Comment by 62832** [comment]
I'm not entirely certain, but this looks to be a problem with ProjectE itself. I'll let the guys in charge of that mod know as well that this is happening and see if anything can be done from their end.

**Comment by TheOddball** [comment]
> I'm not entirely certain, but this looks to be a problem with ProjectE itself. I'll let the guys in charge of that mod know as well that this is happening and see if anything can be done from their end.

That's certainly interesting! Thank you for being so timely in investigating this matter :)

**Comment by 62832** [comment]
Hello again. My suspicions were pretty much confirmed that this is a problem on ProjectE's end. What they're currently doing to query player capabilities for knowledge and EMC actually throws an exception altogether if the cap can't be found, which just so happens to happen when a player on the server is dead.

For the time being, I've rolled out my own fix in the add-on involving a mixin that replaces the offending method with a near-identical copy that instead returns the offline provider instance for that player rather than throwing. However, since I'm not entirely satisfied with this approach I'm going to leave this issue open until the problem is fixed upstream.

**Comment by TheOddball** [comment]
Thank you for fixing this issue so quickly! Major kudos. I'll put together a new version of our pack with the update. Thank you!

**Comment by 62832** [comment]
Just a heads up, you should use the *next* update coming in a few minutes rather than this one since I fucked something up on my end earlier. Look out for 0.6.4-beta coming up.

**Comment by TheOddball** [comment]
Will do!

**Comment by TheOddball** [comment]
[crash-2024-05-05_15.25.10-server.txt](https://github.com/62832/AppliedE/files/15214756/crash-2024-05-05_15.25.10-server.txt)
Uhoh! New crash relating to AE2 after updating to 0.6.4 :(

**Comment by 62832** [comment]
Yeah, I got alerted to it later as well. Turns out my previous already-too-intrusive approach didn't really work in the end and I'm replacing it with something more robust. Give it a few minutes to release.

**Comment by TheOddball** [comment]
After updating to 0?6.5, all crashing issues have stopped occuring! Thank you!

**Comment by TheOddball** [comment]
Good afternoon - We are updating our pack today and it seems AppliedE is crashing our server again :(

[crash-2024-05-13_16.33.49-server.txt](https://github.com/62832/AppliedE/files/15300927/crash-2024-05-13_16.33.49-server.txt)

**Comment by 62832** [comment]
My apologies. Would you tell me if the previous version causes any crashes? You might need to temporarily remove any Transmutation Modules and replace them after updating back to the latest.

**Comment by 62832** [comment]
Alternatively, see if the upcoming release fixes it, and if not please let me know.

**Comment by TheOddball** [comment]
I had tested with 0.11.1 instead of .3, and it still crashed.
Upon updating to 0.11.4, I am now getting a different crash :(
[crash-2024-05-14_10.45.08-server.txt](https://github.com/62832/AppliedE/files/15312121/crash-2024-05-14_10.45.08-server.txt)

**Comment by 62832** [comment]
~~The only thing I can suggest is rolling back to whatever version worked last and removing any Transmutation Modules before updating and then placing them back.~~

Unfortunately, I haven't been able to reproduce this in either my development environment or on another large modpack's test server, and I can only assume this is just a consequence of how frequently (and admittedly rather haphazardly) I've had to change different things around internally.

**Comment by 62832** [comment]
> I tried to break the block > update > replace it, and the server did successfully start when it was broken - however, upon placing, the server instantly crashes.

Okay, now this I think might be on me and fixable, I hope. Give me a few minutes.

**Comment by TheOddball** [comment]
Also - now the server wont start on the old version 😆

**Comment by TheOddball** [comment]
I do not mind waiting for a potential fix included in 0.11.5 :)
