### ISSUE TITLE
ME Transmutation Interface can void EMC when set to stock maximally-valuable items

### ISSUE THREAD

**Issue by James103** [62832/AppliedE#4]
When an ME Transmutation Interface is set to stock a high-value EMC item with a maximum stack size above 1, such as a Final Power Flower or Compact Sun from Project Expansion, the interface will void 1-3 times the EMC value of the item to be requested every second and not provide the item requested (assuming the request is for 1 of that item) or maintain 1 fewer than the amount requested (if the amount requested exceeds 1).

This can lead to mass voiding of EMC when attempting to automatically expand Power Flower setups or automatically performing custom crafts which require items worth quadrillions or quintillions of EMC each.

To reproduce:
1. Install AE2 + AppliedE + ProjectE + Project Expansion.
2. Create a new world with cheats enabled.
3. Run this command: `projecte emc set @s 1000000000000000000000000000`, or get that much EMC via other means.
4. Create an ME Network consisting of a Creative Energy Cell, ME Transmutation Module, ME Transmutation Terminal, and ME Transmutation Interface.
5. Give yourself a Final Power Flower or Compact Sun.
6. Open the ME Transmutation Terminal and dump your inventory into the terminal, making sure to learn the power flower or Compact Sun.
7. In the ME Transmutation Interface, set a request to keep one Final Power Flower or Compact Sun in stock.
8. Watch as the item never materializes yet the player's EMC total keeps dropping.

---

Edit: There is no need for a Transmutation Interface.

1. Install AE2 + AppliedE + ProjectE + Project Expansion.
2. Create a new world with cheats enabled.
3. Create an ME Network consisting of a Creative Energy Cell, ME Transmutation Module, ME Transmutation Terminal, and ME Transmutation Interface.
4. Run `give @s projectexpansion:final_power_flower`
5. Dump the Final Power Flower into the ME Transmutation Terminal (learning it).
6. Run `projecte emc set @s 10000000000000000000`
7. Shift-click the Final Power Flower out of the Transmutation Terminal.
8. Shift-click the resulting stack of Final Power Flowers back into the Transmutation Terminal.
9. Notice one Final Power Flower worth of EMC is voided.

<details>

<summary> Full mod list </summary>

```
  [✔] ae2wtlib-15.2.3-forge
  [✔] appliede-0.9.0-beta
  [✔] appliedenergistics2-forge-15.1.1
  [✔] architectury-9.2.14-forge
  [✔] cloth-config-11.1.118-forge
  [✔] curios-forge-5.9.0+1.20.1
  [✔] jei-1.20.1-forge-15.3.0.4
  [✔] NoChatReports-FORGE-1.20.1-v2.2.2
  [✔] ProjectE-1.20.1-PE1.0.1
  [✔] ProjectExpansion-1.20.1-1.1.0
```

</details>

**Comment by 62832** [comment]
That's not good. Did this happen prior to 0.9.0 as well or was it only now that this bug was introduced?
