### ISSUE TITLE
With 10^(12n) + a small amount in EMC, auto-crafting to auto-transmute fails and puts 10^(12n) EMC and a crafting CPU on hold.

### ISSUE THREAD

**Issue by James103** [62832/AppliedE#7]
For example, with 1,000,000,000,100 EMC available and the ability to request an Iron Ingot be transmuted via auto-crafting, attempting to request that iron ingot (worth 256 EMC) will cause one of the crafting CPUs on the network to lock up and 1,000,000,000,000 EMC to be held in that CPU until its crafting job is canceled or another 1,000,000,000,000 EMC is injected and made available for use in the ME Network.

To reproduce:
1. Install AE2 + AppliedE + ProjectE.
2. Create a new world with cheats enabled.
3. Run this command: `projecte emc set @s 1000000000100`, or get exactly that much EMC via other means.[^1]
4. Create an ME Network consisting of a Creative Energy Cell, ME Transmutation Module, at least one Crafting CPU, and a regular ME storage or crafting terminal.
5. Give yourself two Transmutation Tables.
6. Place one down, and learn the other.
7. Request a Transmutation Table be auto-transmuted through the ME Network's auto-crafting setup.
8. The request will lock up, causing 1,000,000,000,000 EMC to be held inside the Crafting CPU and the requested item not to be given.
9. Give yourself another 1,000,000,000,000 EMC, then open up the ME terminal again.
10. Notice the request completes this time, giving the item and leftover EMC back to the network.

<details>

<summary> Full mod list </summary>

```
ae2wtlib-15.2.3-forge
appliede-0.11.0-beta
appliedenergistics2-forge-15.2.1
architectury-9.2.14-forge
cloth-config-11.1.118-forge
curios-forge-5.9.0+1.20.1
jei-1.20.1-forge-15.3.0.4
NoChatReports-FORGE-1.20.1-v2.2.2
ProjectE-1.20.1-PE1.0.1
ProjectExpansion-1.20.1-1.1.0
```

</details>

[^1]: Running `projecte emc set @s 1000000000000000000000000000000000000000000000000000000000100` is also sufficient to reproduce this, as does adding or removing twelve zeroes at a time to the number before running the command, hence the 10^(12n) in the title instead of 10^12.

**Comment by 62832** [comment]
Thanks for the heads-up, I think I've got a fix already. When 0.11.1 releases, let me know if that sorts it out.

**Comment by 62832** [comment]
0.11.1 should be out now. Thank you for all the thorough testing you've been doing so far.
